## 1. Tqdm 

`tqmd` 是一个快速，可扩展的 `Python` 进度条，可以在 `Python` 长循环中添加一个进度提示信息，用户只需要封装任意的迭代器 `tqdm(iterator)`。

In [3]:
# test
from tqdm import tqdm 
import time
for i in tqdm(range(10000)):  
    time.sleep(0.01)  

100%|██████████| 10000/10000 [01:44<00:00, 95.85it/s]


## 2. numpy.expand_dims的用法

函数通过在指定位置插入新的轴来扩展数组形状。

`expand_dims(a, axis)` 就是在 `axis` 的那一个轴上把数据加上去，这个数据在 `axis` 这个轴的 `0` 位置。 

例如原本为一维的 `2` 个数据，`axis=0`，则 `shape` 变为 `(1,2)`,`axis=1` 则 `shape` 变为 `(2,1)` 

再例如 原本为 `(2,3)`,`axis=0`，则 `shape` 变为 `(1,2,3)`,`axis=1` 则 `shape` 变为`(2,1,3)`

In [5]:
import numpy as np
x = np.array([1,2])
x.shape

(2,)

In [6]:
y = np.expand_dims(x, axis=0)
y

array([[1, 2]])

In [7]:
y.shape

(1, 2)

## 3. Numpy中stack()，hstack()，vstack()函数详解

### 3.1 stack()函数 

函数原型为：`stack(arrays, axis=0)`，`arrays` 可以传数组和列表。

In [9]:
a=[[1,2,3,4],
   [5,6,7,8],
   [9,10,11,12]]

print("列表a如下：")
print(a)

print("增加一维，新维度的下标为0")
c=np.stack(a,axis=0)
print(c)

print("增加一维，新维度的下标为1")
c=np.stack(a,axis=1)
print(c)

列表a如下：
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
增加一维，新维度的下标为0
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
增加一维，新维度的下标为1
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 3.2 hstack()函数 

函数原型：`hstack(tup)` ，参数 `tup` 可以是元组，列表，或者 `numpy` 数组，返回结果为 `numpy` 的数组。

In [10]:
a=[1,2,3]
b=[4,5,6]
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [11]:
a=[[1],[2],[3]]
b=[[1],[2],[3]]
c=[[1],[2],[3]]
d=[[1],[2],[3]]
print(np.hstack((a,b,c,d)))

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


它其实就是水平(按列顺序)把数组给堆叠起来，`vstack()` 函数正好和它相反。

### 3.3 vstack()函数 

函数原型：`vstack(tup)` ，参数 `tup` 可以是元组，列表，或者 `numpy` 数组，返回结果为 `numpy` 的数组。

In [12]:
a=[1,2,3]
b=[4,5,6]
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [13]:
a=[[1],[2],[3]]
b=[[1],[2],[3]]
c=[[1],[2],[3]]
d=[[1],[2],[3]]
print(np.vstack((a,b,c,d)))

[[1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]]


它是垂直（按照行顺序）的把数组给堆叠起来。

## Reference

[Numpy中stack()，hstack()，vstack()函数详解](https://blog.csdn.net/csdn15698845876/article/details/73380803)

[]()

[]()

[]()

[]()

[]()

[]()

[]()

[]()